kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kaas-robot-admin
  namespace: kaas
subjects:
  - kind: ServiceAccount
    name: kaas-robot
    namespace: kaas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
